In [38]:
import pandas as pd
from sklearn.metrics import f1_score, confusion_matrix
import matplotlib.pyplot as plt

In [31]:
original = pd.read_csv("task_A_En_test.csv")
reannotated = pd.read_csv("task_A_test_shuffle_to_annotate.csv")

In [32]:
reannotated

      Unnamed: 0                                               text sarcastic
0              0  Size on the the Toulouse team, That pack is mo...         1
1              1                                           Pinball!         0
2              2  So the Scottish Government want people to get ...         1
3              3  villainous pro tip : change the device name on...         1
4              4                    I would date any of these men 🥺         1
...          ...                                                ...       ...
1395        1395  I’ve just seen this and felt it deserved a Ret...         ?
1396        1396               Omg how an earth is that a pen !!! 🤡         ?
1397        1397          Bringing Kanye and drake to a tl near you         ?
1398        1398  I love it when women are referred to as "girl ...         ?
1399        1399  The fact that people still don't get that you ...         ?

[1400 rows x 3 columns]

In [33]:
merged = original.merge(reannotated, on = "text", suffixes = ("_original", "_reannotated"))

merged = merged[merged["sarcastic_reannotated"] != "?"]

merged["sarcastic_reannotated"] = merged["sarcastic_reannotated"].astype("int64")

merged

                                                  text  ...  sarcastic_reannotated
0    Size on the the Toulouse team, That pack is mo...  ...                      1
1                                             Pinball!  ...                      0
2    So the Scottish Government want people to get ...  ...                      1
3    villainous pro tip : change the device name on...  ...                      1
4                      I would date any of these men 🥺  ...                      1
..                                                 ...  ...                    ...
352  You can tell ted cruz cares about Texas.  He c...  ...                      1
353  “Safety measures” ???? Are they safe? Where’s ...  ...                      0
354  Need to get a foothold only one thing's gunna ...  ...                      0
653  I see all the reasons Mark has put forward and...  ...                      0
793  Im just gonna go out there and say it… Chas an...  ...                      0

[354 rows x 4 columns]

In [40]:
confusion_matrix(merged["sarcastic_original"].array, merged["sarcastic_reannotated"].array)

array([[256,  52],
       [ 11,  35]])

In [35]:
f1_score(merged["sarcastic_original"].array, merged["sarcastic_reannotated"].array, average = None)

array([0.89043478, 0.52631579])